version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
      - ./migrations:/migrations:ro
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:postgres_password@postgres:5432/auth_db
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres_password
      DB_NAME: auth_db
      DB_PORT: 5432
      JWT_SECRET: shared-jwt-secret-key-12345
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - backend

  user-service:
    build: ./user-service
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: postgresql://postgres:postgres_password@postgres:5432/user_db
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres_password
      DB_NAME: user_db
      DB_PORT: 5432
      JWT_SECRET: shared-jwt-secret-key-12345
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - backend

  admin-service:
    build: ./admin-service
    ports:
      - "3003:3003"
    environment:
      DATABASE_URL: postgresql://postgres:postgres_password@postgres:5432/admin_db
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres_password
      DB_NAME: admin_db
      DB_PORT: 5432
      JWT_SECRET: shared-jwt-secret-key-12345
    depends_on:
      - postgres
    networks:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth-service
      - user-service
      - admin-service
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:
